### ISSUE TITLE
Chapter 10 Tutorial - Sound and CombatHUD

### ISSUE THREAD

**Issue by RiverHeart** [HaxeFlixel/flixel-docs#171]
[Chapter 10](https://github.com/HaxeFlixel/flixel-docs/blob/master/documentation/01_tutorial/11-10-ui-and-combat.html.md) of the tutorial points to [Combat.hx](https://github.com/HaxeFlixel/flixel-demos/blob/master/Tutorials/TurnBasedRPG/source/CombatHUD.hx) where the code for the sound files is included before sound is discussed in [Chapter 12](https://github.com/HaxeFlixel/flixel-docs/blob/master/documentation/01_tutorial/13-12-sound-and-music.html.md). It produces errors when building.

A paragraph needs added to Chapter 10 to add Pointer.png to the asset/images path to prevent build errors also.

**Comment by KosnIre** [comment]
I had a number of problems when testing the game at the end of [Part 10](http://haxeflixel.com/documentation/ui-and-combat/). I'm going to list them here, but the sound files in particular might need to be their own Issue.

1. In the HUD Class `import flixel.group.FlxTypedGroup;` should be `import flixel.group.FlxGroup.FlxTypedGroup;` **(fixed by [this change](https://github.com/HaxeFlixel/flixel-docs/commit/3ea01adc110342f9fabf7d16c578b3e401b80cf9), but not yet published)**
- PlayState.hx:116: characters 53-67 : Enemy has no field isFlickering
- PlayState.hx:94: characters 5-25 : Enemy has no field flicker
- CombatHUD.hx:108: characters 90-113 : Class<AssetPaths> has no field pointer__png
- CombatHUD.hx:144: characters 29-49 : Class<AssetPaths> has no field fled__wav
- CombatHUD.hx:145: characters 29-49 : Class<AssetPaths> has no field hurt__wav
- CombatHUD.hx:146: characters 29-49 : Class<AssetPaths> has no field lose__wav
- CombatHUD.hx:147: characters 29-49 : Class<AssetPaths> has no field miss__wav
- CombatHUD.hx:148: characters 31-53 : Class<AssetPaths> has no field select__wav
- CombatHUD.hx:149: characters 28-47 : Class<AssetPaths> has no field win__wav
- CombatHUD.hx:150: characters 31-53 : Class<AssetPaths> has no field combat__wav

I have created [a pull request to correct numbers 2 & 3](https://github.com/HaxeFlixel/flixel-docs/pull/183).

Number 4 is easy to correct, since a link to the graphic can be added as is done in other sections of the Tutorial.

That just leaves the sound files unaddressed...

**Comment by KosnIre** [comment]
The sound files is a problem that is a bit more difficult to solve. I see a few options:

**A**. Add links to download the sound files in Section 10. 
_This feels wrong to me, since sound isn't covered until Section 12. However, it may be the simplest._

**B.** Leave out the sound code from the `CombatHUD` file and have the student add this code later (during Section 12). 
_This maintains the general workflow of the Tutorial, but could be problematic because the `CombatHUD` file is being downloaded directly from the demo source code, which needs that functionality._

**C.** Add an argument to the `CombatHUD` constructor that can optionally turn the sound code on/off (e.g. `?playSounds:Bool=false`)
_Since the compiler is throwing errors for the missing files, this doesn't seem to be possible._

**D.** Reorder the Tutorial, so that Sound and Music immediately follows UI and Combat. Let the student know that "although there are compilation errors right now, we will cover that in the next section."
_Ideally each Section should result in a functional / testable iteration of the game._

**E.** Other options?

**Comment by KosnIre** [comment]
Interesting. In [Section 12](http://haxeflixel.com/documentation/sound-and-music/), there _are_ instructions to add all the sound code to the `CombatHUD` class. That might lend credence to Option **B**, if we can find a good place to store the partially-complete file (although storing 2 becomes a maintenance issue).

**Comment by KosnIre** [comment]
I have an idea for how to fix this using Option **A**. I'm going to try to work on it tomorrow, and propose the change via a PR.
