### ISSUE TITLE
please use a better search engine

### ISSUE THREAD

**Issue by raould** [HaxeFlixel/flixel-docs#199]
i am finding the search ux to be not useful for me personally. for me it would just be better if the search text field were a front for just doing a Google query restricted by "site:http://api.haxeflixel.com".

**Comment by Gama11** [comment]
The search box is provided by [Dox](https://github.com/HaxeFoundation/dox), so it would be better to open an issue there instead.

If you do, it would be good if you provided some more details. I quite like the search box myself - what's your problem with it? Do you want to search by keywords on the pages rather than just filter by type name?
